input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "platform" => "autohealai" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "autohealai-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
